/**
 * Converts an image path/URL to a Base64 string.
 * This is useful for embedding images in PDFs generated by jsPDF.
 */
export const imageToBase64 = (url) => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.setAttribute("crossOrigin", "anonymous");
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = (error) => {
      reject(error);
    };
    const separator = url.includes("?") ? "&" : "?";
    img.src = `${url}${separator}t=${new Date().getTime()}`;
  });
};

export const rotateImage90Deg = (url) => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.setAttribute("crossOrigin", "anonymous");
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.height;
      canvas.height = img.width;
      const ctx = canvas.getContext("2d");
      ctx.translate(canvas.width / 2, canvas.height / 2);
      ctx.rotate((-90 * Math.PI) / 180);
      ctx.drawImage(img, -img.width / 2, -img.height / 2);

      // Background removal & coloring signature stamp-blue
      try {
        const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imgData.data;

        // Check if the image already has transparent pixels
        let hasTransparency = false;
        for (let i = 3; i < data.length; i += 4) {
          if (data[i] < 220) {
            hasTransparency = true;
            break;
          }
        }

        // Only process background removal if it does not already have transparency
        if (!hasTransparency) {
          for (let i = 0; i < data.length; i += 4) {
            const r = data[i];
            const g = data[i + 1];
            const b = data[i + 2];
            const minVal = Math.min(r, g, b);

            if (minVal > 95) {
              if (minVal >= 165) {
                data[i + 3] = 0;
              } else {
                data[i + 3] = Math.round(255 * (1 - (minVal - 95) / (165 - 95)));
              }
            }
          }
        }

        // Darken the signature color to rich dark blue
        for (let i = 0; i < data.length; i += 4) {
          if (data[i + 3] > 30) {
            data[i] = Math.max(0, Math.round(data[i] * 0.3));     // R
            data[i + 1] = Math.max(0, Math.round(data[i + 1] * 0.3)); // G
            data[i + 2] = Math.max(80, Math.round(data[i + 2] * 0.9)); // B (keep rich blue)
          }
        }

        // Thicken (dilate) the signature lines to make it bold (2px thickness)
        const width = canvas.width;
        const height = canvas.height;
        const alphaCopy = new Uint8Array(width * height);
        for (let y = 0; y < height; y++) {
          for (let x = 0; x < width; x++) {
            alphaCopy[y * width + x] = data[(y * width + x) * 4 + 3];
          }
        }

        for (let y = 2; y < height - 2; y++) {
          for (let x = 2; x < width - 2; x++) {
            const idx = (y * width + x) * 4;
            if (alphaCopy[y * width + x] < 50) {
              let maxAlpha = 0;
              for (let dy = -2; dy <= 2; dy++) {
                for (let dx = -2; dx <= 2; dx++) {
                  const val = alphaCopy[(y + dy) * width + (x + dx)];
                  if (val > maxAlpha) maxAlpha = val;
                }
              }
              if (maxAlpha > 50) {
                data[idx + 3] = maxAlpha;
                data[idx] = 10;
                data[idx + 1] = 30;
                data[idx + 2] = 120;
              }
            }
          }
        }

        ctx.putImageData(imgData, 0, 0);
      } catch (err) {
        console.warn("Background removal failed", err);
      }

      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = (error) => {
      reject(error);
    };
    const separator = url.includes("?") ? "&" : "?";
    img.src = `${url}${separator}t=${new Date().getTime()}`;
  });
};
